name: Check for broken links

on:
  workflow_dispatch: # only run manually

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker 🔗
        uses: lycheeverse/lychee-action@v1.9.0
        with:
          fail: true
          args: --user-agent 'curl/7.54' --exclude-path README.md --exclude-path _pages/404.md --exclude-path _pages/blog.md --exclude-path _layouts --exclude-path _includes --exclude-path _demo --exclude-path CUSTOMIZE.md --verbose --no-progress './**/*.md' './**/*.html'
